name: Build and deploy ASP.Net Core app to Azure Web App - web-api-thell-u3

on:
  push:
    branches:
      - main
    paths:
      - 'web-api-thell-u3/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        working-directory: ./web-api-thell-u3
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./web-api-thell-u3
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'web-api-thell-u3'
          slot-name: 'Production'
          package: .
  tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run smoke test
        run: |
          echo "Running smoke test..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://web-api-thell-u3-smoketest.azurewebsites.net/api/SmokeTest)
          if [ "$response" != "200" ]; then
            echo "Smoke test failed with status: $response"
            exit 1
          fi
          echo "Smoke test passed!"
          